### ISSUE TITLE
Monitoring a remote pihole from a non-pihole RPi

### ISSUE THREAD

**Issue by h2o82** [santoru/pihole-dashboard#13]
Hi,

Everything installed OK however the epaper flashes every minute to update and does not display any text, just a white screen.

When running the` sudo pihole-dashboard-draw` I get the following:

```
Traceback (most recent call last):
  File "/usr/local/bin/pihole-dashboard-draw", line 23, in <module>
    pihole_dashboard.update()
  File "/usr/local/lib/python3.9/dist-packages/pihole_dashboard/__init__.py", line 134, in update
    process = subprocess.Popen(cmd.split(), stdout=subprocess.PIPE)
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1823, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/bin/pihole'

```
Environment:

- Raspberry Pi 4, Waveshare 2.13in V3 (confirmed working with examples from waveshare)
- Pihole version 5.17.3
- Pihole instance running on a docker on the localhost
- Tried another docker instance on another host. (I run 2 pihole's for redundancy).
- Pihole ports both are 8008 (changed in the config.toml)
- Pihole API key present in the config.toml
- Changed network interface in config.toml to "eth0" (my network connection)

Can you advise on the issue or supply some hints?

**Comment by ViperTK** [comment]
I've the same issue with latest pihole running in docker on another Pi
